# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: landmarks.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'landmarks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flandmarks.proto\x12\x12\x61lice.telemetry.v1\"\x82\x01\n\x14LandmarkStreamHeader\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x16\n\x0elandmark_count\x18\x02 \x01(\r\x12\x12\n\nsource_fps\x18\x03 \x01(\x02\x12\x19\n\x11keyframe_interval\x18\x04 \x01(\r\x12\x12\n\nframe_skip\x18\x05 \x01(\r\"?\n\x08KeyFrame\x12\x14\n\x0c\x66rame_number\x18\x01 \x01(\r\x12\x0e\n\x02xy\x18\x02 \x03(\rB\x02\x10\x01\x12\r\n\x01z\x18\x03 \x03(\x11\x42\x02\x10\x01\"C\n\nDeltaFrame\x12\x14\n\x0c\x66rame_number\x18\x01 \x01(\r\x12\x0f\n\x03\x64xy\x18\x02 \x03(\x11\x42\x02\x10\x01\x12\x0e\n\x02\x64z\x18\x03 \x03(\x11\x42\x02\x10\x01\"#\n\x0bNoFaceFrame\x12\x14\n\x0c\x66rame_number\x18\x01 \x01(\r\"\xa1\x01\n\x05\x46rame\x12+\n\x03key\x18\x01 \x01(\x0b\x32\x1c.alice.telemetry.v1.KeyFrameH\x00\x12/\n\x05\x64\x65lta\x18\x02 \x01(\x0b\x32\x1e.alice.telemetry.v1.DeltaFrameH\x00\x12\x32\n\x07no_face\x18\x03 \x01(\x0b\x32\x1f.alice.telemetry.v1.NoFaceFrameH\x00\x42\x06\n\x04kind\":\n\rLandmarkChunk\x12)\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x19.alice.telemetry.v1.Frameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'landmarks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYFRAME'].fields_by_name['xy']._loaded_options = None
  _globals['_KEYFRAME'].fields_by_name['xy']._serialized_options = b'\020\001'
  _globals['_KEYFRAME'].fields_by_name['z']._loaded_options = None
  _globals['_KEYFRAME'].fields_by_name['z']._serialized_options = b'\020\001'
  _globals['_DELTAFRAME'].fields_by_name['dxy']._loaded_options = None
  _globals['_DELTAFRAME'].fields_by_name['dxy']._serialized_options = b'\020\001'
  _globals['_DELTAFRAME'].fields_by_name['dz']._loaded_options = None
  _globals['_DELTAFRAME'].fields_by_name['dz']._serialized_options = b'\020\001'
  _globals['_LANDMARKSTREAMHEADER']._serialized_start=40
  _globals['_LANDMARKSTREAMHEADER']._serialized_end=170
  _globals['_KEYFRAME']._serialized_start=172
  _globals['_KEYFRAME']._serialized_end=235
  _globals['_DELTAFRAME']._serialized_start=237
  _globals['_DELTAFRAME']._serialized_end=304
  _globals['_NOFACEFRAME']._serialized_start=306
  _globals['_NOFACEFRAME']._serialized_end=341
  _globals['_FRAME']._serialized_start=344
  _globals['_FRAME']._serialized_end=505
  _globals['_LANDMARKCHUNK']._serialized_start=507
  _globals['_LANDMARKCHUNK']._serialized_end=565
# @@protoc_insertion_point(module_scope)
